---
- name: Upgrade Nexus
  hosts: localhost
  become_user: nexus
  become: yes
  tasks:
    - name: Stop Nexus
      shell: echo "Stopping Nexus"
    
    - name: Backup Nexus
      shell: echo "Backing up Nexus"

    - name: Upgrade Nexus
      shell: echo "Upgrading Nexus"

    - name: Start Nexus
      shell: echo "Starting Nexus"
      
